### ISSUE TITLE
npm ERR! Missing script: "dev"

### ISSUE THREAD

**Issue by Umairyousaf0098** [vedees/react-cv-builder-tocode#1]
npm run dev
npm ERR! Missing script: "dev"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: C:\Users\Sohail Laptop\AppData\Local\npm-cache\_logs\2024-04-23T06_53_46_346Z-debug-0.log

**Comment by vedees** [comment]
Use `npm run start` or `yarn start`

**Comment by vedees** [comment]
UPD: added `dev` tag. You can use `npm run dev`...
